---
title: "SciVal data prep"
author: "Tom Tullius"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

load_file <- function(path) {
  vroom::vroom(path, delim = ",")
}

fileInput("file1",
                "Choose CSV File with Trainee metadata",
                accept = ".csv"
      )

meta_df <- reactive({
  load_file(input$file1$datapath)
})

meta_df


```


```{r}
library (dplyr)

#df1<-read.csv("graduated_students_SciVal_cleaned.csv", header = TRUE)
df1<- read.csv(here::here("data", "processed", "2023_03_Bioinformatics_metadata_cleaned.csv"))
head(df1)


#df2<-read.csv("2023_03_Bioinformatics_metadata_cleaned.csv", header = TRUE)
df2<-read.csv(here::here("data", "processed", "graduated_students_SciVal_cleaned.csv"))
head(df2)

df12<- left_join(df1, df2, by = 'Author')
head(df12)

head(df12)
write.csv(df12, file = "BUResearchers_full.csv")
```



```{r}
library(dplyr)

#df3<-read.csv("1_75_Scholarly_Output_vs_Publication_Year.csv", header = TRUE)
df3 <- read.csv(here::here("data", "raw", "full_paper_list_outputs","1_75_Scholarly_Output_vs_Publication_Year.csv"))
head(df3)

#df2<-read.csv("76_150_Scholarly_Output_vs_Publication_Year.csv", header = TRUE)
df4 <- read.csv(here::here("data", "raw", "full_paper_list_outputs", "76_150_Scholarly_Output_vs_Publication_Year.csv"))
head(df4)

full_df34 <- union(df3, df4)
head(full_df34)

#df3<-read.csv("150_Scholarly_Output_vs_Publication_Year.csv", header = TRUE)
df5 <- read.csv(here::here("data", "raw",  "full_paper_list_outputs", "150_Scholarly_Output_vs_Publication_Year.csv"))
df5

full_df345 <- union(full_df34, df5)
head(full_df345)
write.csv(full_df345, file = "all_papers_out.csv")
```



```{r}
library(dplyr)
library(tidyverse)

trainees_meta <- read_csv(here::here("/Users/tom/Dropbox (BOSTON UNIVERSITY)/R/SciVal_Shiny/data/BUResearchers_full.csv"))
trainees_papers <- read.csv(here::here("/Users/tom/Dropbox (BOSTON UNIVERSITY)/R/SciVal_Shiny/data/all_papers_out.csv"))

#trainees_papers <- select(trainees_papers, -X, -Author, -first, -starts_with("X19"))
trainees_papers <- select(trainees_papers, -X, -Author, -first,)
trainees_papers <- trainees_papers |> rename_with(.fn = ~ str_replace(.x, "X", ""),
            .cols = starts_with("X"))

df_all_papers <- trainees_meta %>% inner_join(trainees_papers, by = 'ID')
df_all_papers <- select(df_all_papers, -Student_Name, -First)
df_all_papers <- select(df_all_papers, 1:24)
as_tibble(df_all_papers)

write_csv(df_all_papers, file = "BUResearchers_meta__papers.csv")

```

